
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: orc_user
      POSTGRES_PASSWORD: orc_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - app-network
