version: "3.9"

services:

  fingerprint-db:
    image: postgres:16
    environment:
      POSTGRES_USER: fingerprint_user
      POSTGRES_PASSWORD: fingerprint_pass
      POSTGRES_DB: fingerprint_db
    volumes:
      - fingerprint_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  orchestration-db:
    image: postgres:16
    environment:
      POSTGRES_USER: orch_user
      POSTGRES_PASSWORD: orch_pass
      POSTGRES_DB: orchestration_db
    volumes:
      - orchestration_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  fingerprint-service:
    build: ./fingerprint-service
    depends_on:
      - fingerprint-db
    environment:
      DATABASE_URL: postgresql://fingerprint_user:fingerprint_pass@fingerprint-db:5432/fingerprint_db
    ports:
      - "8000:8000"

  orchestration-service:
    build: ./orchestration-service
    depends_on:
      - orchestration-db
      - fingerprint-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://orchestration-db:5432/orchestration_db
      SPRING_DATASOURCE_USERNAME: orch_user
      SPRING_DATASOURCE_PASSWORD: orch_pass
      FINGERPRINT_SERVICE_URL: http://fingerprint-service:8000/index
      JWT_SECRET: supersecretkeysupersecretkeysupersecretkey
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"

volumes:
  fingerprint_data:
  orchestration_data:
